name: "Dev deployment"
on: [workflow_dispatch]
jobs:
  deploy_dev:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Read Ruby version
        id: ruby-version
        run: echo "ruby-version=$(cat .ruby-version)" >> $GITHUB_ENV
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
      - name: "Deploy dev"
        env:
          name: dev
          url: "https://dev.queens-awards-enterprise.service.gov.uk/"
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_SPACE: dev
          CF_APP: qae-dev
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -v -L -o cf-cli_amd64.deb "$CF_PACKAGE_URL"
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          ./bin/deploy
